version: "3"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "America/Sao_Paulo"
    restart: unless-stopped

  nginx-node-app:
    image: nginx:1.24.0-alpine-slim
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/conf.d/node-app.conf:/etc/nginx/conf.d/node-app.conf:ro
    ports:
      - 7080:80
    depends_on:
       - node-app
    restart: unless-stopped